version: '3.8'

services:
  eureka-0:
    build: ./eureka-server
    container_name: eureka-0
    hostname: eureka-0
    ports:
      - "8761:8761"
    environment:
      - EUREKA_INSTANCE_HOSTNAME=eureka-0
      - EUREKA_PEERS=http://eureka-0:8761/eureka/,http://eureka-1:8761/eureka/

  eureka-1:
    build: ./eureka-server
    container_name: eureka-1
    hostname: eureka-1
    ports:
      - "8762:8761"
    environment:
      - EUREKA_INSTANCE_HOSTNAME=eureka-1
      - EUREKA_PEERS=http://eureka-0:8761/eureka/,http://eureka-1:8761/eureka/
