server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:eureka}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_PEERS:http://eureka-0:8761/eureka/,http://eureka-1:8761/eureka/}
  server:
    enable-self-preservation: false
